from django.db import models
from django.shortcuts import reverse
from django.utils.text import slugify
from time import time

def gen_slug(s):
    new_slug = slugify(s, allow_unicode=True)
    return new_slug+'-'+str(int(time()))


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=150, db_index=True)
    #unique - this means that the column cannot have duplicates and the column will have automatically indexation
    slug = models.SlugField(max_length=150, blank=True, unique=True)
    #blank=True - it means that the column may contain empty values
    body = models.TextField(blank=True, db_index=True)
    date_pub =  models.DateTimeField(auto_now_add=True)
    #Model of interaction between classes ManyToMany;
    #blank=True it means that class of post may not have Tags
    #related_name='posts' --> related/implant the value posts into class Tag. if don't do it  the value will automatically be generated by django
    tags=models.ManyToManyField('Tag', blank=True, related_name='posts')

    def get_update_url(self):
        return reverse('post_update_url', kwargs={'slug': self.slug})

    #URL reversion  equel  href="{% url 'post_detail_url' slug=post.slug %}"
    def get_absolute_url(self):
        return reverse('post_detail_url', kwargs={'slug': self.slug})

    # This method __srt__ is used when you need to print some element of an object.
    # method __str__ override the method of string, and you can set the showing format
    def __str__ (self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug =  gen_slug(self.title)
        super().save(*args, **kwargs)

class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)

    #URL reversion  equel  href="{% url 'post_detail_url' slug=post.slug %}"
    def get_absolute_url(self):
        return reverse('tag_detail_url', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('tag_update_url', kwargs={'slug': self.slug})

    def __str__ (self):
        return '{}'.format(self.title)
